package UI;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Estudiant
 */

import javax.swing.ImageIcon;
import java.awt.Image;
import java.net.URL;

public class VPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VPrincipal.class.getName());
    
    /**
     * Creates new form VPrincipal
     */
    public VPrincipal() {
         // 1. ESTABLECER TÍTULO DE LA VENTANA
        this.setTitle("Mi Aplicación - Acceso al Sistema");
        
        // 2. ESTABLECER ICONO DE LA VENTANA (IMAGEN)
        establecerIconoVentana();
        
        // Establecemos el panel de fondo personalizado
        this.setContentPane(new FondoPanel());
        
        initComponents();
        
        this.setResizable(false);
        this.setSize(750, 700);
        
        // 3. APLICAR ESTILOS A LOS JLABEL
        EstiloUI.estiloJLabelPrincipal(jLabel1, "Pulse el botón para acceder a la página web");
        // Si quieres cambiar el texto original, descomenta la línea de abajo
        // EstiloUI.estiloJLabelNormal(jLabel1, "Haga click en el botón para acceder a la página");
        
        // Aplicamos estilos centralizados
        EstiloUI.estiloPanelContenedor(jPanel2);
        EstiloUI.estiloBotonPrincipal(btnAbrir);
        
        // Transparencia necesaria para el layout
        jPanel1.setOpaque(false);
        
        this.setLocationRelativeTo(null);
    }
    
    private void establecerIconoVentana() {
        try {
            // Intentamos cargar el recurso
            URL iconURL = getClass().getResource("/resources/iconoDiagnosis.png");

            if (iconURL != null) {
                ImageIcon icono = new ImageIcon(iconURL);
                // IMPORTANTE: No es estrictamente necesario hacer el ScaledInstance para el icono de la barra
                // Windows y macOS suelen redimensionarlo automáticamente mejor que el código.
                this.setIconImage(icono.getImage());
                this.setIconImages(java.util.Arrays.asList(icono.getImage()));
            } else {
                // Este log te dirá en la consola si realmente no está encontrando el archivo
                System.err.println("Error: No se encontró el archivo en /resources/iconoDiagnosis.png");
                this.setIconImage(crearIconoPorDefecto());
            }
        } catch (Exception e) {
            System.err.println("Excepción al cargar el icono: " + e.getMessage());
            this.setIconImage(crearIconoPorDefecto());
        }
    }
    
    private java.awt.Image crearIconoPorDefecto() {
        java.awt.image.BufferedImage img = new java.awt.image.BufferedImage(64, 64, java.awt.image.BufferedImage.TYPE_INT_ARGB);
        java.awt.Graphics2D g2d = img.createGraphics();
        g2d.setColor(EstiloUI.ROJO_IES);
        g2d.fillRect(0, 0, 64, 64);
        g2d.setColor(java.awt.Color.WHITE);
        g2d.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 30));
        g2d.drawString("App", 12, 42);
        g2d.dispose();
        return img;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new FondoPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAbrir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pulse el botón para acceder a la página web");
        jLabel1.setToolTipText("");
        jLabel1.setAlignmentY(0.0F);

        btnAbrir.setBackground(new java.awt.Color(200, 30, 30));
        btnAbrir.setForeground(new java.awt.Color(255, 255, 255));
        btnAbrir.setText("Abrir");
        btnAbrir.setAlignmentY(1.0F);
        btnAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbrir.addActionListener(this::btnAbrirActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addComponent(btnAbrir)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 46;
        gridBagConstraints.ipady = 109;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(81, 150, 124, 133);
        jPanel1.add(jPanel2, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
      // Simplemente llamamos al método que creamos en la lógica
        logic.Navegacion.abrirPagina();
    }//GEN-LAST:event_btnAbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
